<?php

namespace Abigah\BotCopTrafficDivision\Support;

use Carbon\Carbon;
use Carbon\CarbonInterface;
use Illuminate\Support\Str;

/**
 * The outcome of one uptime check, whoever performed it.
 *
 * The seam this package replays through is a single method, and this is what it
 * takes. A locally performed check and one delivered by a prober arrive as the
 * same object, so nothing downstream — thresholds, incidents, deployment
 * windows, notifications — has any way to tell them apart or any reason to.
 *
 * `checkedAt` is the point of it. A delivered result carries the moment it was
 * actually taken, not the moment it arrived, so a batch that was buffered for
 * an hour replays as the hour it describes.
 */
class CheckResult
{
    public function __construct(
        public readonly bool $up,
        public readonly CarbonInterface $checkedAt,
        public readonly ?int $responseTimeMs = null,
        public readonly ?string $failureReason = null,
        public readonly ?int $statusCode = null,

        /**
         * A 200 that never reached the origin. Carried beside `up` rather than
         * as a third status, because a cached success is still a response — it
         * is the configuration that is wrong, and that is worth surfacing
         * separately rather than folding into an outage.
         */
        public readonly bool $servedFromCache = false,

        /** Null when this check was performed by this application itself. */
        public readonly ?string $proberId = null,
        public readonly ?string $location = null,

        /**
         * A ULID, generated by whoever performed the check. Ingest is
         * idempotent on it, and it sorts in time order so an interrupted
         * delivery can resume from the last one accepted.
         */
        public readonly string $checkId = '',
    ) {}

    public static function up(
        ?int $responseTimeMs = null,
        ?CarbonInterface $checkedAt = null,
        ?int $statusCode = 200,
        bool $servedFromCache = false,
    ): self {
        return new self(
            up: true,
            checkedAt: $checkedAt ?? Carbon::now(),
            responseTimeMs: $responseTimeMs,
            statusCode: $statusCode,
            servedFromCache: $servedFromCache,
            checkId: (string) Str::ulid(),
        );
    }

    public static function down(
        ?string $failureReason = null,
        ?int $responseTimeMs = null,
        ?CarbonInterface $checkedAt = null,
        ?int $statusCode = null,
    ): self {
        return new self(
            up: false,
            checkedAt: $checkedAt ?? Carbon::now(),
            responseTimeMs: $responseTimeMs,
            failureReason: $failureReason,
            statusCode: $statusCode,
            checkId: (string) Str::ulid(),
        );
    }

    /**
     * One row of a delivered `results` payload, as the contract defines it.
     *
     * @param  array<string, mixed>  $row
     * @param  array{id: string, location: string}  $prober
     */
    public static function fromResultsPayload(array $row, array $prober): self
    {
        return new self(
            up: (bool) $row['up'],
            checkedAt: Carbon::parse($row['checked_at']),
            responseTimeMs: $row['response_time_ms'] ?? null,
            failureReason: $row['failure_reason'] ?? null,
            statusCode: $row['status_code'] ?? null,
            servedFromCache: (bool) ($row['served_from_cache'] ?? false),
            proberId: $prober['id'],
            location: $prober['location'],
            checkId: $row['check_id'],
        );
    }

    /** @return array<string, mixed> */
    public function toCheckAttributes(): array
    {
        return [
            'check_id' => $this->checkId !== '' ? $this->checkId : (string) Str::ulid(),
            'status' => $this->up ? 'up' : 'down',
            'response_time_ms' => $this->responseTimeMs,
            'status_code' => $this->statusCode,
            'failure_reason' => $this->up ? null : $this->failureReason,
            'served_from_cache' => $this->servedFromCache,
            'prober_id' => $this->proberId,
            'location' => $this->location,
            'checked_at' => $this->checkedAt,
        ];
    }
}
