<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('monitor_checks', function (Blueprint $table) {
            $table->id();

            /*
             | A ULID, generated by whoever performed the check. Delivered
             | results are idempotent on it and the prober advances its cursor
             | by it, which is why it has to sort in time order — a UUID here
             | would break ordered replay silently.
             |
             | Local checks generate one too, so nothing downstream has to care
             | which mode produced a row.
             */
            $table->char('check_id', 26)->unique();

            $table->foreignId('monitor_id')->constrained('monitors')->cascadeOnDelete();
            $table->string('status'); // up, down
            $table->unsignedInteger('response_time_ms')->nullable();
            $table->unsignedSmallInteger('status_code')->nullable();
            $table->text('failure_reason')->nullable();

            // A 200 that never reached the origin. Carried beside `status`
            // rather than as a third status value, because the seam this
            // package replays through takes a boolean.
            $table->boolean('served_from_cache')->default(false);

            /*
             | Null in local mode. `location` is a label the prober declares and
             | this side only stores and displays — nothing infers anything from
             | it, which is what lets a second prober appear without a schema
             | change.
             */
            $table->string('prober_id')->nullable();
            $table->string('location')->nullable();

            /*
             | A failure only one prober saw, while another said up in the same
             | window. It is kept as history and shown as degraded, but it did
             | not advance the state machine and did not open an incident: a
             | route between one data centre and one origin is not the site.
             */
            $table->boolean('disagreed')->default(false);

            $table->timestamp('checked_at');

            $table->index(['monitor_id', 'checked_at']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('monitor_checks');
    }
};
